apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

iam:
  withOIDC: true

metadata:
  name: canary-cluster
  region: ap-south-1
  version: "1.30"

managedNodeGroups:
  - name: ng-dedicated-1
    instanceType: t3a.xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        awsLoadBalancerController: true
        certManager: true
        externalDNS: true
        ebs: true
  - name: ng-spot-1
    instanceTypes:
    - t2.xlarge
    - t3.xlarge
    - t3a.xlarge
    desiredCapacity: 5
    spot: true
    labels:
      role: spot
    iam:
      withAddonPolicies:
        autoScaler: true
        awsLoadBalancerController: true
        certManager: true
        externalDNS: true
        ebs: true